### PR TITLE
Site name

### LINKED ISSUE #80: Make Header customizable
- [ ] Create a new constant `const siteName = "Prixite"` in [data.ts](https://github.com/prixite/prixite.github.io/blob/master/constants/data.ts).
- [ ] Use `siteName` in https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js#L66
- [ ] Use `siteName` in https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js#L80

### PR DESCRIPTION
**Pull request by BenDundon**
Closes #80 

> - [x] Create a new constant const siteName = "Prixite" in [data.ts](https://github.com/prixite/prixite.github.io/blob/master/constants/data.ts).
> - [x] Use siteName in https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js#L66
> - [x] Use siteName in https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js#L80

Once merged, will happily implement the changes for #81 too

### CODE REVIEW

**Comment by umairwaheed** [comment]
@BenDundon thanks for the PR. Can you please resolve the conflicts?

**Review by umairwaheed — CHANGES_REQUESTED** [review]
Resolve conflicts.

**Comment by BenDundon** [comment]
Conflicts resolved & successfully merged with the recent changes

**Review by umairwaheed — APPROVED** [review]
Thank you. LGTM.

**Pull request merged**
