### PR TITLE
change header to typescript

### LINKED ISSUE #64: [TypeScript] Change Header.js to TypeScript
Change [Header.js](https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js) to TypeScript.

- [ ] Change name to Header.tsx.
- [ ] Change code from JavaScript to TypeScript.

### PR DESCRIPTION
**Pull request by fpetrakov**
This change resolves #64 by changing header from javascript to typescript.
Signed-off-by: Fedya Petrakov

### CODE REVIEW

**Comment by fpetrakov** [comment]
There are 3 typescript errors left though

**Comment by umairwaheed** [comment]
Thanks @fpetrakov for the PR. We will review it shortly.

**Comment by umairwaheed** [comment]
@fpetrakov can you please resolve conflicts?

**Review by umairwaheed — CHANGES_REQUESTED** [review]
Need to resolve conflicts.

**Comment by umairwaheed** [comment]
Fixed via https://github.com/prixite/prixite.github.io/pull/85

**Pull request closed without merging**
