### PR TITLE
Fixing issue #53 - added Head component to Header.js 

### PR DESCRIPTION
**Pull request by rkoalsi**
I've added the head component to the Header.js file, passed the title as props and have removed the imports of Head wherever not used in the pages directory.

### CODE REVIEW

**Comment by umairwaheed** [comment]
Thanks @rkoalsi . I will merge PR once https://github.com/prixite/prixite.github.io/pull/56 is merged.

**Comment by umairwaheed** [comment]
@rkoalsi we have merged https://github.com/prixite/prixite.github.io/pull/56. Can you please get the latest changes from upstream/master?

**Comment by rkoalsi** [comment]
@umairwaheed task complete from my end.

**Review by umairwaheed — APPROVED** [review]
Looks good. Thank you @rkoalsi

**Pull request merged**
