### PR TITLE
fix #66 - Constants to data

### LINKED ISSUE #66: Change constants to data
Change [constants.js](https://github.com/prixite/prixite.github.io/blob/master/constants/constants.js) to data/data.ts. 

- [ ] Rename filename
- [ ] Change code to TypeScript.
- [ ] Change references in the codebase.

### PR DESCRIPTION
**Pull request by michalstruck**
Renamed file didn't need typing, as it's all easily inferred as string. Closes #66.

### CODE REVIEW

**Comment by umairwaheed** [comment]
@michalstruck can you please resolve conflicts?

**Comment by michalstruck** [comment]
Done

**Comment by umairwaheed** [comment]
@michalstruck I am getting the following error when I try to run `yarn dev`. This happens on portfolio page. This error doesn't happen on upstream/master branch.

```
ReferenceError: Box is not defined
  11 |     <div className="portfolio-page">
  12 |       <Header bgImg={homePageBg} title={title}>
> 13 |         <Box className="careers-container">
     |         ^
  14 |           <Typography
  15 |             variant="h2"
  16 |             textAlign="center"
```

**Review by umairwaheed — CHANGES_REQUESTED** [review]
There is an error that needs to be fixed.

**Review by umairwaheed — APPROVED** [review]
LGTM

**Pull request merged**
